# -*- coding: utf-8 -*-
"""spellGram v2.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xuzleDylUGQQKWB3QnBqF83GoYXglcvC
"""

# !pip install transformers

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
tokenizer = AutoTokenizer.from_pretrained("prithivida/grammar_error_correcter_v1")
model = AutoModelForSeq2SeqLM.from_pretrained("prithivida/grammar_error_correcter_v1")

input_ids = tokenizer("You're refund should be credited on Thursday", return_tensors="pt").input_ids
outputs = model.generate(input_ids)
ans = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(ans, type(ans))

